export const accordiandata = [
  {
    id: 1,
    question: "What is the difference between FAQ and FAQPAge Schema Markup?",
    answer:
      "AFAIK they are the same thing. Schema.org calls it FAQPage and Google refers to it as both FAQ and FAQPages.",
  },
  {
    id: 2,
    question: "Looking for FAQ schema markup example?",
    answer:
      "Here is the FAQ Schema markup used on this page, you can also see this in Google by searching for",
  },
  {
    id: 3,
    question: "What is the difference between FAQ and QA Schema Markup?",
    answer:
      "FAQ and QA are two different structured data markups that can be used on your page to get rich results in Google search results. While they sound similar they have a slightly different purpose.",
  },
  {
    id: 4,
    question:
      "How can I get FAQPage to work with Google assistant powered devices?",
    answer:
      "The FAQPage code generated by this FAQ Page Schema Generator tool will be picked up by both Google Search and Google Assistant powered devices.",
  },
];
